import type { PlanGraph, PresentationSpec } from "@/types/contracts";

const src = (label: string) => ({
  type: "catalog" as const,
  label,
  accessedAt: new Date().toISOString(),
});

export const DEMO_PRESENTATION: PresentationSpec = {
  suggestedArtDirection: "circuit_board",
  artDirectionReason: "CS major — luminous traces map your prerequisite chain.",
  heroMessage: "5 semesters to your CS degree — let's make them count.",
  colorAccent: "#06B6D4",
  emphasisItems: [
    {
      type: "heavy_semester",
      nodeIds: ["node-cs3214"],
      title: "Spring 2027 load",
      description: "Systems + Algorithms stack — plan extra study blocks.",
      priority: 1,
    },
  ],
  nodeAnnotations: [
    {
      nodeId: "node-cs4624",
      text: "Strong fit for your ML interest and morning schedule preference.",
      tone: "tip",
    },
  ],
  semesterAnnotations: [
    {
      term: { year: 2027, termType: "spring", label: "Spring 2027" },
      text: "Critical path semester — keep prerequisites intact.",
      tone: "warning",
    },
  ],
};

export const DEMO_PLAN_GRAPH: PlanGraph = {
  id: "demo-graph",
  studentId: "demo",
  nodes: [
    {
      id: "node-cs2114",
      courseId: "CS-2114",
      status: "completed",
      semester: { year: 2025, termType: "fall", label: "Fall 2025" },
      score: 92,
      scoreBreakdown: { rating: 9, rigorMatch: 8, timeFit: 9, graduationSpeed: 10 },
      confidence: "high",
      alternatives: [],
      requirementBlockId: "cs-core",
      warnings: [],
      sources: [src("Catalog")],
    },
    {
      id: "node-cs2505",
      courseId: "CS-2505",
      status: "completed",
      semester: { year: 2026, termType: "spring", label: "Spring 2026" },
      score: 88,
      scoreBreakdown: { rating: 8, rigorMatch: 7, timeFit: 9, graduationSpeed: 9 },
      confidence: "high",
      alternatives: [],
      requirementBlockId: "cs-core",
      warnings: [],
      sources: [src("Catalog")],
    },
    {
      id: "node-cs3114",
      courseId: "CS-3114",
      status: "in_progress",
      semester: { year: 2026, termType: "fall", label: "Fall 2026" },
      instructor: "Dr. Chen",
      score: 85,
      scoreBreakdown: { rating: 8, rigorMatch: 9, timeFit: 7, graduationSpeed: 9 },
      confidence: "medium",
      alternatives: [
        { courseId: "CS-3114", instructor: "Dr. Smith", score: 82, reason: "Earlier section, slightly lower RMP." },
      ],
      requirementBlockId: "cs-core",
      warnings: ["Historic offering: usually Fall only"],
      sources: [src("Timetable")],
    },
    {
      id: "node-cs3214",
      courseId: "CS-3214",
      status: "planned_next",
      semester: { year: 2027, termType: "spring", label: "Spring 2027" },
      sectionCrn: "12345",
      instructor: "Prof. Rivera",
      score: 90,
      scoreBreakdown: { rating: 9, rigorMatch: 8, timeFit: 8, graduationSpeed: 10 },
      confidence: "high",
      alternatives: [
        { courseId: "CS-3214", instructor: "Dr. Park", score: 86, reason: "Better time fit, moderate difficulty." },
      ],
      requirementBlockId: "cs-core",
      warnings: [],
      sources: [src("RMP")],
    },
    {
      id: "node-cs4624",
      courseId: "CS-4624",
      status: "planned_future",
      semester: { year: 2027, termType: "fall", label: "Fall 2027" },
      instructor: "Dr. Nguyen",
      score: 87,
      scoreBreakdown: { rating: 9, rigorMatch: 7, timeFit: 8, graduationSpeed: 8 },
      confidence: "medium",
      alternatives: [],
      requirementBlockId: "cs-elective",
      warnings: [],
      sources: [src("RMP")],
    },
    {
      id: "node-cs4604",
      courseId: "CS-4604",
      status: "planned_future",
      semester: { year: 2028, termType: "spring", label: "Spring 2028" },
      score: 84,
      scoreBreakdown: { rating: 8, rigorMatch: 8, timeFit: 7, graduationSpeed: 9 },
      confidence: "low",
      alternatives: [
        { courseId: "CS-4254", score: 80, reason: "Networking alternative if DB section fills." },
      ],
      requirementBlockId: "cs-elective",
      warnings: ["Rare summer offering — keep in Spring"],
      sources: [src("Historic timetable")],
    },
  ],
  edges: [
    { from: "node-cs2114", to: "node-cs2505", type: "prerequisite" },
    { from: "node-cs2505", to: "node-cs3114", type: "prerequisite" },
    { from: "node-cs3114", to: "node-cs3214", type: "prerequisite" },
    { from: "node-cs3214", to: "node-cs4624", type: "prerequisite" },
    { from: "node-cs3114", to: "node-cs4604", type: "prerequisite" },
  ],
  semesters: [
    {
      term: { year: 2025, termType: "fall", label: "Fall 2025" },
      nodeIds: ["node-cs2114"],
      totalCredits: 3,
      warnings: [],
    },
    {
      term: { year: 2026, termType: "spring", label: "Spring 2026" },
      nodeIds: ["node-cs2505"],
      totalCredits: 3,
      warnings: [],
    },
    {
      term: { year: 2026, termType: "fall", label: "Fall 2026" },
      nodeIds: ["node-cs3114"],
      totalCredits: 3,
      warnings: [],
    },
    {
      term: { year: 2027, termType: "spring", label: "Spring 2027" },
      nodeIds: ["node-cs3214"],
      totalCredits: 3,
      warnings: ["Heavy prerequisite chain"],
    },
    {
      term: { year: 2027, termType: "fall", label: "Fall 2027" },
      nodeIds: ["node-cs4624"],
      totalCredits: 3,
      warnings: [],
    },
    {
      term: { year: 2028, termType: "spring", label: "Spring 2028" },
      nodeIds: ["node-cs4604"],
      totalCredits: 3,
      warnings: [],
    },
  ],
  totalRemainingCredits: 12,
  estimatedGraduation: { year: 2028, termType: "spring", label: "Spring 2028" },
  generatedAt: new Date().toISOString(),
  verifierPassed: true,
  verifierIssues: [],
};

export const DEMO_COURSE_TITLES: Record<string, { title: string; credits: number }> = {
  "CS-1114": { title: "Introduction to Software Design", credits: 3 },
  "CS-2104": { title: "Problem Solving in Computer Science", credits: 3 },
  "CS-2114": { title: "Software Design and Data Structures", credits: 3 },
  "CS-2505": { title: "Intro to Computer Organization", credits: 3 },
  "CS-2506": { title: "Computer Organization II", credits: 3 },
  "CS-3114": { title: "Data Structures and Algorithms", credits: 3 },
  "CS-3214": { title: "Computer Systems", credits: 3 },
  "CS-3304": { title: "Comparative Languages", credits: 3 },
  "CS-3744": { title: "Intro to GUI Design and Development", credits: 3 },
  "CS-4104": { title: "Data and Algorithm Analysis", credits: 3 },
  "CS-4114": { title: "Formal Languages and Automata Theory", credits: 3 },
  "CS-4254": { title: "Computer Network Architecture", credits: 3 },
  "CS-4264": { title: "Principles of Computer Security", credits: 3 },
  "CS-4284": { title: "Systems and Networking Capstone", credits: 3 },
  "CS-4604": { title: "Introduction to Database Systems", credits: 3 },
  "CS-4624": { title: "Multimedia, Hypertext, and Info Access", credits: 3 },
  "CS-4644": { title: "Creative Computing Studio", credits: 3 },
  "CS-4654": { title: "Intermediate Data Analytics and ML", credits: 3 },
  "CS-4784": { title: "Human-Computer Interaction", credits: 3 },
  "MATH-1225": { title: "Calculus of a Single Variable", credits: 3 },
  "MATH-1226": { title: "Calculus of Several Variables", credits: 3 },
  "MATH-2114": { title: "Intro to Linear Algebra", credits: 3 },
  "MATH-2204": { title: "Intro to Multivariable Calculus", credits: 3 },
  "STAT-4705": { title: "Statistics for Engineering Applications", credits: 3 },
  "PHYS-2305": { title: "Foundations of Physics I", credits: 4 },
  "PHYS-2306": { title: "Foundations of Physics II", credits: 4 },
  "ENGL-1105": { title: "First-Year Writing", credits: 3 },
  "ENGL-1106": { title: "First-Year Writing Seminar", credits: 3 },
  "ENGL-2014": { title: "Intro to Literary Studies", credits: 3 },
  "PHIL-2014": { title: "Introduction to Philosophy", credits: 3 },
  "PSYC-2004": { title: "Introductory Psychology", credits: 3 },
  "COMM-1016": { title: "Communication for Professionals", credits: 3 },
  "HIST-1114": { title: "U.S. History to 1865", credits: 3 },
  "HIST-1214": { title: "U.S. History since 1865", credits: 3 },
  "SOC-1004": { title: "Introductory Sociology", credits: 3 },
  "PSCI-1014": { title: "U.S. Government and Politics", credits: 3 },
  "ECON-2005": { title: "Principles of Economics", credits: 3 },
  "ECON-2006": { title: "Principles of Economics (Micro)", credits: 3 },
  "AAEC-1005": { title: "Economics of the Food and Fiber System", credits: 3 },
  "GEO-1004": { title: "Physical Geology", credits: 3 },
  "BIOL-1105": { title: "Principles of Biology", credits: 3 },
  "CHEM-1035": { title: "General Chemistry", credits: 3 },
  "GEOS-1004": { title: "Physical Geology", credits: 3 },
  "ISE-1004": { title: "Engineering Economy", credits: 3 },
  "ART-1014": { title: "Visual Foundations Studio", credits: 3 },
  "MUS-1014": { title: "Intro to Music Technology", credits: 3 },
  "TA-1014": { title: "Theatre Appreciation", credits: 3 },
  "ARCH-1016": { title: "Design Appreciation", credits: 3 },
  "CINE-2054": { title: "Intro to Cinema", credits: 3 },
  "FL-2104": { title: "Intermediate Foreign Language", credits: 3 },
  "GEO-2404": { title: "Geography of the World", credits: 3 },
  "AFST-1024": { title: "Intro to Africana Studies", credits: 3 },
  "WGS-1024": { title: "Intro to Women and Gender Studies", credits: 3 },
  "RLCL-1014": { title: "Religions of the World", credits: 3 },
  // New CS electives
  "CS-3704": { title: "Intermediate Software Design", credits: 3 },
  "CS-3654": { title: "Intro Data Analytics & Visualization", credits: 3 },
  "CS-4204": { title: "Computer Graphics", credits: 3 },
  "CS-4274": { title: "Introduction to Cryptography", credits: 3 },
  "CS-4304": { title: "Compiler Design", credits: 3 },
  "CS-4414": { title: "Issues in Computer Science", credits: 3 },
  "CS-4634": { title: "Design of Information", credits: 3 },
  "CS-4804": { title: "Introduction to Artificial Intelligence", credits: 3 },
  "CS-4824": { title: "Machine Learning with Big Data", credits: 3 },
  "CS-4884": { title: "Computational Biology", credits: 3 },
  // More pathways courses
  "PHIL-1304": { title: "Knowledge and Reality", credits: 3 },
  "PHIL-1204": { title: "Moral Reasoning", credits: 3 },
  "HIST-1024": { title: "Intro to World History", credits: 3 },
  "ENGL-2114": { title: "Reading & Writing About Literature", credits: 3 },
  "REL-1014": { title: "Introduction to Religion", credits: 3 },
  "HUM-1204": { title: "Humanities Seminar", credits: 3 },
  "GEOG-1014": { title: "Introduction to Geography", credits: 3 },
  "UAP-1024": { title: "Intro to Urban Affairs", credits: 3 },
  "PSCI-1024": { title: "Government and Politics", credits: 3 },
  "IS-2054": { title: "Global Cultures", credits: 3 },
  "GEOS-1024": { title: "Earth Materials and Resources", credits: 3 },
  "BIOL-1004": { title: "General Biology", credits: 3 },
  "BIOL-1014": { title: "Principles of Biology (Non-Majors)", credits: 3 },
  "PHYS-1055": { title: "Physics of Today's World", credits: 3 },
  "NR-1004": { title: "Earth, Life, and Time", credits: 3 },
  "ART-1044": { title: "Intro to Digital Art", credits: 3 },
  "MUS-1054": { title: "World Music", credits: 3 },
  "TA-1044": { title: "Dramatic Art and Society", credits: 3 },
  "CINE-2064": { title: "Digital Filmmaking", credits: 3 },
  "CREA-2184": { title: "Creative Technologies", credits: 3 },
  "SPAN-2104": { title: "Intermediate Spanish", credits: 3 },
  "AINS-1024": { title: "Intro to American Indian Studies", credits: 3 },
  "ALCE-1004": { title: "Learning and Culture in Education", credits: 3 },
  "APSC-1024": { title: "Appalachian Studies", credits: 3 },
  // Free electives
  "ENGE-1024": { title: "Engineering Exploration", credits: 2 },
  "ENGE-1215": { title: "Foundations of Engineering", credits: 2 },
  "UNIV-1004": { title: "University Seminar", credits: 1 },
  "LDRS-1015": { title: "Foundations of Leadership", credits: 1 },
  "HNFE-1004": { title: "Introduction to Human Nutrition", credits: 3 },
  "HTM-1014": { title: "Hospitality and Tourism Management", credits: 3 },
  "BIT-2405": { title: "Intro to Business Analytics", credits: 3 },
  "ACIS-1504": { title: "Introduction to Business", credits: 3 },
  "EDCI-1014": { title: "Exploring Education", credits: 3 },
  "HD-1004": { title: "Introduction to Human Development", credits: 3 },
  "SPIA-2004": { title: "Public Policy", credits: 3 },
  "DASC-1004": { title: "Intro to Data Science", credits: 3 },
  "CMDA-2005": { title: "Integrated Quantitative Sciences", credits: 3 },
  "MATH-2534": { title: "Intro to Discrete Mathematics", credits: 3 },
  "STAT-4714": { title: "Probability & Statistics for Engineers", credits: 3 },
};
